on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  securityCheck:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Secret Scanning
        id: trufflehog
        uses: edplato/trufflehog-actions-scan@master
        continue-on-error: true
        with:
          scanArguments: "--regex --entropy=False --max_depth=5 --rules /regexes.json" # Add custom options here*

