name: ZAP

on:
  push:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  ZAP:
    runs-on: ubuntu-latest
    steps:
      - name: DAST OWASP ZAP scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
        # Target URL
          target: https://secdevops10-bb7deefad445.herokuapp.com/#/
